# Generated by Django 4.0.4 on 2022-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
